import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

/* ==========================================================
   CONFIGURATION
========================================================== */


export const PARISH_INFO = {
  name: "Our Lady of Peace and Good Voyage Parish",
  address: "Lodlod, Lipa City, Batangas",
  logo: path.join(process.cwd(), "frontend/public/logotest.png"),
  footerNote: "·",
  theme: {
    primary: "CA141D", // red
    secondary: "FDE2E4", // light pink / light red background
    accent: "8B0000", // dark red
    headerText: "FFFFFF", // white
    text: "333333", // dark gray
    border: "CCCCCC", // light gray
  },
};

/* ==========================================================
   EXCEL REPORT GENERATOR (Enhanced Design)
========================================================== */
export async function generateExcelReport(
  data,
  columns,
  title,
  outPath,
  metadata = {}
) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet("Report", {
    pageSetup: {
      paperSize: 9, // A4
      orientation: "landscape",
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
    },
  });

  const { primary, secondary, accent, headerText, text, border } =
    PARISH_INFO.theme;

  // Set default column widths
  ws.columns = columns.map(() => ({ width: 15 }));

  let currentRow = 1;

  // ============= PARISH HEADER =============
  ws.mergeCells(
    `A${currentRow}`,
    `${String.fromCharCode(64 + columns.length)}${currentRow}`
  );
  ws.getCell(`A${currentRow}`).value = PARISH_INFO.name.toUpperCase();
  ws.getCell(`A${currentRow}`).font = {
    bold: true,
    size: 18,
    color: { argb: "FF" + accent },
    name: "Calibri",
  };
  ws.getCell(`A${currentRow}`).alignment = {
    horizontal: "center",
    vertical: "middle",
  };
  ws.getRow(currentRow).height = 30;
  currentRow++;

  // Address
  ws.mergeCells(
    `A${currentRow}`,
    `${String.fromCharCode(64 + columns.length)}${currentRow}`
  );
  ws.getCell(`A${currentRow}`).value = PARISH_INFO.address;
  ws.getCell(`A${currentRow}`).font = {
    size: 11,
    color: { argb: "FF666666" },
    name: "Calibri",
  };
  ws.getCell(`A${currentRow}`).alignment = { horizontal: "center" };
  currentRow++;

  // Separator line
  ws.mergeCells(
    `A${currentRow}`,
    `${String.fromCharCode(64 + columns.length)}${currentRow}`
  );
  ws.getCell(`A${currentRow}`).fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF" + primary },
  };
  ws.getRow(currentRow).height = 3;
  currentRow++;

  // Empty row
  currentRow++;

  // ============= TITLE =============
  ws.mergeCells(
    `A${currentRow}`,
    `${String.fromCharCode(64 + columns.length)}${currentRow}`
  );
  ws.getCell(`A${currentRow}`).value = title;
  ws.getCell(`A${currentRow}`).font = {
    bold: true,
    size: 16,
    color: { argb: "FF" + text },
    name: "Calibri",
  };
  ws.getCell(`A${currentRow}`).alignment = {
    horizontal: "center",
    vertical: "middle",
  };
  ws.getRow(currentRow).height = 25;
  currentRow++;

  // ============= METADATA =============
  if (metadata && Object.keys(metadata).length > 0) {
    currentRow++;
    const metaStartRow = currentRow;
    const metaData = [
      `Generated By: ${metadata.generatedBy || "System"}`,
      `Generated On: ${metadata.generatedAt || new Date().toLocaleString()}`,
      `Total Records: ${metadata.totalRecords || data.length}`,
      metadata.dateRange ? `Date Range: ${metadata.dateRange}` : null,
      metadata.scope && metadata.scope !== "all"
        ? `Scope: ${metadata.scope}`
        : null,
    ].filter(Boolean);

    metaData.forEach((meta) => {
      ws.mergeCells(
        `A${currentRow}`,
        `${String.fromCharCode(64 + columns.length)}${currentRow}`
      );
      ws.getCell(`A${currentRow}`).value = meta;
      ws.getCell(`A${currentRow}`).font = {
        size: 10,
        color: { argb: "FF555555" },
        name: "Calibri",
      };
      ws.getCell(`A${currentRow}`).alignment = {
        horizontal: "center",
        vertical: "middle",
        wrapText: true,
      };
      ws.getCell(`A${currentRow}`).fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF" + secondary },
      };
      ws.getRow(currentRow).height = Math.min(
        Math.max((meta.length / 20) * 15, 15),
        40
      ); // dynamic height
      currentRow++;
    });

    for (let r = metaStartRow; r < currentRow; r++) {
      ws.getCell(`A${r}`).border = {
        top:
          r === metaStartRow
            ? { style: "thin", color: { argb: "FF" + border } }
            : undefined,
        bottom:
          r === currentRow - 1
            ? { style: "thin", color: { argb: "FF" + border } }
            : undefined,
        left: { style: "thin", color: { argb: "FF" + border } },
        right: { style: "thin", color: { argb: "FF" + border } },
      };
    }
  }

  currentRow++;

  // ============= TABLE HEADER =============
  const headerRow = ws.addRow(columns.map((c) => c.header));
  headerRow.height = 20;
  headerRow.eachCell((cell, colNumber) => {
    cell.font = {
      bold: true,
      color: { argb: "FF" + headerText },
      size: 11,
      name: "Calibri",
    };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF" + primary },
    };
    cell.alignment = {
      horizontal: "center",
      vertical: "middle",
      wrapText: true,
    };
    cell.border = {
      top: { style: "medium", color: { argb: "FF" + accent } },
      left: { style: "thin", color: { argb: "FF" + headerText } },
      bottom: { style: "medium", color: { argb: "FF" + accent } },
      right: { style: "thin", color: { argb: "FF" + headerText } },
    };
  });

  // ============= DATA ROWS =============
  data.forEach((rowData, index) => {
    const row = ws.addRow(
      columns.map((c) => {
        let value = rowData[c.key];
        if (value instanceof Date) value = value.toLocaleDateString("en-PH");
        return value ?? "N/A";
      })
    );

    row.eachCell((cell, colIndex) => {
      const text = String(cell.value);
      cell.alignment = {
        horizontal: "center",
        vertical: "middle",
        wrapText: true,
      };
      cell.font = { size: 10, name: "Calibri" };

      // Dynamically adjust row height based on text length
      const approxLines = Math.ceil(
        text.length / (ws.getColumn(colIndex + 1).width * 1.2)
      );
      row.height = Math.max(18, approxLines * 15);

      // Alternating row colors
      if (index % 2 === 0)
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FFF9F9F9" },
        };

      // Cell borders
      cell.border = {
        top: { style: "thin", color: { argb: "FFE0E0E0" } },
        left: { style: "thin", color: { argb: "FFE0E0E0" } },
        bottom: { style: "thin", color: { argb: "FFE0E0E0" } },
        right: { style: "thin", color: { argb: "FFE0E0E0" } },
      };

      // Status-based coloring
      const cellValue = text.toLowerCase();
      if (cellValue === "completed" || cellValue === "approved") {
        cell.font = { ...cell.font, color: { argb: "FF28A745" }, bold: true };
      } else if (cellValue === "pending") {
        cell.font = { ...cell.font, color: { argb: "FFFFC107" }, bold: true };
      } else if (cellValue === "cancelled" || cellValue === "rejected") {
        cell.font = { ...cell.font, color: { argb: "FFDC3545" }, bold: true };
      }
    });
  });

  // ============= AUTO-ADJUST COLUMN WIDTHS =============
  columns.forEach((col, i) => {
    const maxLength = Math.max(
      col.header.length,
      ...data.map((r) => String(r[col.key] || "").length)
    );
    ws.getColumn(i + 1).width = Math.min(Math.max(maxLength + 3, 12), 50);
  });

  // ============= FOOTER =============
  const footerRow = ws.lastRow.number + 2;
  ws.mergeCells(
    `A${footerRow}`,
    `${String.fromCharCode(64 + columns.length)}${footerRow}`
  );
  ws.getCell(`A${footerRow}`).value = `${
    PARISH_INFO.footerNote
  } • Generated on ${new Date().toLocaleString("en-PH", {
    timeZone: "Asia/Manila",
  })}`;
  ws.getCell(`A${footerRow}`).font = {
    italic: true,
    size: 9,
    color: { argb: "FF888888" },
    name: "Calibri",
  };
  ws.getCell(`A${footerRow}`).alignment = { horizontal: "center" };

  await wb.xlsx.writeFile(outPath);
  return outPath;
}

export async function generatePdfReport(
  data,
  columns,
  title,
  outPath,
  metadata = {}
) {
  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
    layout: "landscape",
    bufferPages: true,
  });

  const stream = fs.createWriteStream(outPath);
  doc.pipe(stream);

  const { logo, name, address, footerNote } = PARISH_INFO;
  const pageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const pageHeight =
    doc.page.height - doc.page.margins.top - doc.page.margins.bottom;

  // ================= HEADER =================
  const addHeader = () => {
    if (fs.existsSync(logo)) {
      try {
        doc.image(logo, 40, 35, { width: 45, height: 45 });
      } catch {
        console.log("Logo not found, skipping...");
      }
    }

    doc
      .font("Helvetica-Bold")
      .fontSize(16)
      .fillColor("#1A5490")
      .text(name.toUpperCase(), 100, 40, { align: "left" });

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#666666")
      .text(address, 100, 60, { align: "left" });

    doc
      .moveTo(40, 85)
      .lineTo(doc.page.width - 40, 85)
      .strokeColor("#2E75B6")
      .lineWidth(2)
      .stroke();
  };

  // ================= FOOTER =================
  const addFooter = (pageNum, totalPages) => {
    const footerY = doc.page.height - 40;
    doc
      .fontSize(8)
      .fillColor("#888888")
      .text(
        `${footerNote} • Generated on ${new Date().toLocaleString("en-PH", {
          timeZone: "Asia/Manila",
        })}`,
        40,
        footerY,
        { align: "center", width: pageWidth }
      );
    doc.fontSize(8).text(`Page ${pageNum} of ${totalPages}`, 0, footerY + 12, {
      align: "center",
    });
  };

  // ================= START =================
  addHeader();

  doc.moveDown(3);
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor("#1A5490")
    .text(title, { align: "center" });

  // ================= METADATA =================
  if (metadata && Object.keys(metadata).length > 0) {
    doc.moveDown(1.5);
    const metaY = doc.y;
    const metaBoxHeight = 60;
    doc
      .rect(40, metaY, pageWidth, metaBoxHeight)
      .fillAndStroke("#E8F0F8", "#2E75B6");

    doc.font("Helvetica").fontSize(9).fillColor("#333333");
    let textY = metaY + 10;
    const metaInfo = [
      `Generated By: ${metadata.generatedBy || "System"}`,
      `Generated On: ${metadata.generatedAt || new Date().toLocaleString()}`,
      `Total Records: ${metadata.totalRecords || data.length}`,
      metadata.dateRange ? `Date Range: ${metadata.dateRange}` : null,
    ].filter(Boolean);

    metaInfo.forEach((info) => {
      doc.text(info, 50, textY, { align: "left" });
      textY += 12;
    });
    doc.y = metaY + metaBoxHeight + 15;
  } else {
    doc.moveDown(2);
  }

  // ================= TABLE =================
  const startY = doc.y;
  const colWidth = pageWidth / columns.length;
  const defaultRowHeight = 20;

  // Draw table header
  doc
    .rect(40, startY, pageWidth, defaultRowHeight)
    .fillAndStroke("#2E75B6", "#1A5490");
  doc.font("Helvetica-Bold").fontSize(9).fillColor("white");
  columns.forEach((col, i) => {
    doc.text(col.header, 40 + i * colWidth + 2, startY + 6, {
      width: colWidth - 4,
      align: "center",
    });
  });

  let y = startY + defaultRowHeight;
  doc.font("Helvetica").fontSize(8).fillColor("#333333");

  data.forEach((row, idx) => {
    // Calculate max height for this row
    let rowHeight = defaultRowHeight;
    columns.forEach((col) => {
      const text = String(row[col.key] ?? "N/A");
      const textHeight = doc.heightOfString(text, { width: colWidth - 4 });
      rowHeight = Math.max(rowHeight, textHeight + 6); // +6 for padding
    });

    // Page break if row overflows
    if (y + rowHeight > pageHeight) {
      addFooter(doc.bufferedPageRange().start + 1, "X"); // placeholder
      doc.addPage();
      addHeader();
      y = 120;

      // Redraw header
      doc
        .rect(40, y, pageWidth, defaultRowHeight)
        .fillAndStroke("#2E75B6", "#1A5490");
      doc.font("Helvetica-Bold").fontSize(9).fillColor("white");
      columns.forEach((col, i) =>
        doc.text(col.header, 40 + i * colWidth + 2, y + 6, {
          width: colWidth - 4,
          align: "center",
        })
      );
      y += defaultRowHeight;
      doc.font("Helvetica").fontSize(8).fillColor("#333333");
    }

    // Alternating row background
    if (idx % 2 === 0) doc.rect(40, y, pageWidth, rowHeight).fill("#F9F9F9");

    // Draw each cell
    columns.forEach((col, i) => {
      let text = String(row[col.key] ?? "N/A");

      // Status coloring
      const lowerText = text.toLowerCase();
      if (lowerText === "completed" || lowerText === "approved")
        doc.fillColor("#28A745");
      else if (lowerText === "pending") doc.fillColor("#FFC107");
      else if (lowerText === "cancelled" || lowerText === "rejected")
        doc.fillColor("#DC3545");
      else doc.fillColor("#333333");

      doc.text(text, 40 + i * colWidth + 2, y + 3, {
        width: colWidth - 4,
        align: "center",
        lineBreak: true,
      });
    });

    y += rowHeight;
  });

  // ================= FINALIZE =================
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    addFooter(i + 1, range.count);
  }

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(outPath));
    stream.on("error", reject);
  });
}
